TrajectoryPlannerROS:
  max_vel_x: 0.1
  min_vel_x: 0.05
  max_vel_theta: 0.5
  min_in_place_vel_theta: 0.2

  acc_lim_theta: 3.2
  acc_lim_x: 2.5
  acc_lim_y: 2.5

  occdist_scale: 0.8

  holonomic_robot: false
