grid_map_topic: /elevation_map_manipulated

grid_map_visualizations:

  - name: elevation_grid
    type: occupancy_grid
    params:
      layer: elevation_fused
      data_min: 0.14 ##0.14
      data_max: 0.13 #0.13






    



