global_costmap:
  #resolution: 0.05
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 2.0
  
  static_map: true
  rolling_window: false
  width: 5
  height: 10

  plugins:
    - {name: static_layer,  type: "costmap_2d::StaticLayer"}
    - {name: inflation_layer,  type: "costmap_2d::InflationLayer"}
  
  static_layer: 
    enabled: true
    map_topic: "/grid_map_visualization/elevation_grid"
    first_map_only:         false
    lethal_cost_threshold:  50
    subscribe_to_updates:   false
    track_unknown_space:    true
    use_maximum:            false     
    trinary_costmap:        false 

  inflation_layer:
    enabled:  True
    cost_scaling_factor: 5
    inflation_radius: 0.0 


 
  
