local_costmap:
  #resolution: 0.1
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 2.0

  static_map: false
  rolling_window: true
  width: 2
  height: 2
  

  #inflation_radius: 0.3

  plugins:
    - {name: static_layer,  type: "costmap_2d::StaticLayer"}
    - {name: inflation_layer,  type: "costmap_2d::InflationLayer"}
  
  static_layer: 
    enabled: true
    map_topic: "/grid_map_visualization/elevation_grid"
    first_map_only:         false
    lethal_cost_threshold:  50
    subscribe_to_updates:   false
    track_unknown_space:    false
    use_maximum:            false     
    trinary_costmap:        false 

  inflation_layer:
    enabled:  True
    cost_scaling_factor: 5
    inflation_radius: 0.6 