obstacle_range: 3.0
raytrace_range: 3.5

#footprint: [[-0.205, -0.155], [-0.205, 0.155], [0.077, 0.155], [0.077, -0.155]]
robot_radius: 0.3

inflation_radius: 0.2

track_unknown_space: true
observation_sources: scan
scan: {sensor_frame: camera_depth_frame, data_type: PointCloud2, topic: /camera/depth/points_downsampled, marking: true, clearing: true, max_obstacle_height: 0.1, min_obstacle_height: 0.00}
